[package]
name = "advent-of-code-2024"
version = "0.1.0"
edition = "2021"

[dependencies]

[profile.release]
strip = true
opt-level = 3
lto = "fat"
codegen-units = 1
overflow-checks = false
debug = "none"
panic = "abort"
